# Generated by Django 4.2 on 2025-01-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={},
        ),
    ]
