# Generated by Django 4.2 on 2025-01-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_appointments', '0002_alter_slot_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
