# Generated by Django 4.2 on 2025-01-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_appointments', '0002_alter_slot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'managed': False},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='reserved_at',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_id',
            new_name='slot_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='sss', max_length=255),
            preserve_default=False,
        ),
    ]
