# Generated by Django 4.2 on 2025-01-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_appointments', '0003_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='slot',
            table='doctor_availability_slots',
        ),
    ]
