# Generated by Django 4.2 on 2025-01-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_appointments', '0004_alter_slot_options_alter_slot_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'managed': False},
        ),
    ]
