# Generated by Django 4.2 on 2025-01-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_appointments', '0005_alter_slot_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slot',
            table='doctor_availability_slot',
        ),
    ]
