# Generated by Django 4.2 on 2025-01-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_appointments', '0006_alter_slot_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('specialization', models.CharField(db_column='specialization', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=100)),
                ('phone', models.CharField(db_column='phone', max_length=15)),
            ],
            options={
                'db_table': 'doctor_availability_doctor',
                'managed': False,
            },
        ),
    ]
