# Generated by Django 4.2 on 2025-01-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slotId', models.IntegerField()),
                ('patientId', models.IntegerField()),
                ('patientName', models.CharField(max_length=255)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='booked', max_length=15)),
            ],
        ),
    ]
