# Generated by Django 4.2 on 2025-01-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointment_management', '0002_rename_patientid_appointmentmanagement_patient_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmanagement',
            old_name='patientName',
            new_name='patient_name',
        ),
    ]
