# Generated by Django 4.2 on 2025-01-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_confirmation_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
    ]
